[package]
name = "decancer_sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
decancer = "3.2.8"
rusqlite = { version = "0.33.0", features = [ "loadable_extension", "functions", "trace" ] } 

[lib]
crate-type = ["cdylib"]
